 # This module was auto-generated by cpu_interrupts.nim
import std/tables

type
  CpuIrq* = object
    id*: int
    name*: string
    description*: string

type CpuIrqN* = enum
  irqReserved0 = -16
  irqReset = -15
  irqNonMaskableInt = -14
  irqHardFault = -13
  irqMemoryManagement = -12
  irqBusFault = -11
  irqUsageFault = -10
  irqSecureFault = -9
  irqReserved8 = -8
  irqReserved9 = -7
  irqReserved10 = -6
  irqSVCall = -5
  irqDebugMonitor = -4
  irqReserved11 = -3
  irqPendSV = -2
  irqSysTick = -1

const CpuIrqTable*: Table[string, set[CpuIrqN]] = {
  "CM0": {irqReset, irqNonMaskableInt, irqHardFault, irqSVCall, irqPendSV, irqSysTick},
  "CM0PLUS": {irqReset, irqNonMaskableInt, irqHardFault, irqSVCall, irqPendSV, irqSysTick},
  "CM0P": {irqReset, irqNonMaskableInt, irqHardFault, irqSVCall, irqPendSV, irqSysTick},
  "CM1": {irqReset, irqNonMaskableInt, irqHardFault, irqSVCall, irqPendSV, irqSysTick},
  "SC000": {irqReset, irqNonMaskableInt, irqHardFault, irqSVCall, irqPendSV, irqSysTick},
  "CM3": {irqReset, irqNonMaskableInt, irqHardFault, irqMemoryManagement, irqBusFault, irqUsageFault, irqSVCall, irqDebugMonitor, irqPendSV, irqSysTick},
  "SC300": {irqReset, irqNonMaskableInt, irqHardFault, irqMemoryManagement, irqBusFault, irqUsageFault, irqSVCall, irqDebugMonitor, irqPendSV, irqSysTick},
  "CM4": {irqReset, irqNonMaskableInt, irqHardFault, irqMemoryManagement, irqBusFault, irqUsageFault, irqSVCall, irqDebugMonitor, irqPendSV, irqSysTick},
  "CM7": {irqReset, irqNonMaskableInt, irqHardFault, irqMemoryManagement, irqBusFault, irqUsageFault, irqSVCall, irqDebugMonitor, irqPendSV, irqSysTick},
  "CM33": {irqReset, irqNonMaskableInt, irqHardFault, irqMemoryManagement, irqBusFault, irqUsageFault, irqSecureFault, irqSVCall, irqDebugMonitor, irqPendSV, irqSysTick},
  "CM23": {irqReset, irqNonMaskableInt, irqHardFault, irqSVCall, irqPendSV, irqSysTick},
  "CM35": {irqReset, irqNonMaskableInt, irqHardFault, irqMemoryManagement, irqBusFault, irqUsageFault, irqSecureFault, irqSVCall, irqDebugMonitor, irqPendSV, irqSysTick},
  "CM35P": {irqReset, irqNonMaskableInt, irqHardFault, irqMemoryManagement, irqBusFault, irqUsageFault, irqSecureFault, irqSVCall, irqDebugMonitor, irqPendSV, irqSysTick},
  "V8MML": {irqReset, irqNonMaskableInt, irqHardFault, irqMemoryManagement, irqBusFault, irqUsageFault, irqSecureFault, irqSVCall, irqDebugMonitor, irqPendSV, irqSysTick},
  "V8MBL": {irqReset, irqNonMaskableInt, irqHardFault, irqSVCall, irqPendSV, irqSysTick},
  "V81MML": {irqReset, irqNonMaskableInt, irqHardFault, irqMemoryManagement, irqBusFault, irqUsageFault, irqSecureFault, irqSVCall, irqDebugMonitor, irqPendSV, irqSysTick},
  "CM55": {irqReset, irqNonMaskableInt, irqHardFault, irqMemoryManagement, irqBusFault, irqUsageFault, irqSecureFault, irqSVCall, irqDebugMonitor, irqPendSV, irqSysTick},
  "CM85": {irqReset, irqNonMaskableInt, irqHardFault, irqMemoryManagement, irqBusFault, irqUsageFault, irqSecureFault, irqSVCall, irqDebugMonitor, irqPendSV, irqSysTick},
}.toTable

const CpuIrqArray*: array[CpuIrqN, CpuIrq] = [
  irqReserved0: CpuIrq(id: 16, name: "Reserved0", description: "Stack Top is loaded from first entry of vector Table on Reset"),
  irqReset: CpuIrq(id: 15, name: "Reset", description: "Reset Vector, invoked on Power up and warm reset"),
  irqNonMaskableInt: CpuIrq(id: 14, name: "NonMaskableInt", description: "Non maskable Interrupt, cannot be stopped or preempted"),
  irqHardFault: CpuIrq(id: 13, name: "HardFault", description: "Hard Fault, all classes of Fault"),
  irqMemoryManagement: CpuIrq(id: 12, name: "MemoryManagement", description: "Memory Management, MPU mismatch, including Access Violation and No Match"),
  irqBusFault: CpuIrq(id: 11, name: "BusFault", description: "Bus Fault, Pre-Fetch-, Memory Access Fault, other address/memory related Fault"),
  irqUsageFault: CpuIrq(id: 10, name: "UsageFault", description: "Usage Fault, i.e. Undef Instruction, Illegal State Transition"),
  irqSecureFault: CpuIrq(id: 9, name: "SecureFault", description: "Secure Fault Handler"),
  irqReserved8: CpuIrq(id: 8, name: "Reserved8", description: "Reserved - do not use"),
  irqReserved9: CpuIrq(id: 7, name: "Reserved9", description: "Reserved - do not use"),
  irqReserved10: CpuIrq(id: 6, name: "Reserved10", description: "Reserved - do not use"),
  irqSVCall: CpuIrq(id: 5, name: "SVCall", description: "System Service Call via SVC instruction"),
  irqDebugMonitor: CpuIrq(id: 4, name: "DebugMonitor", description: "Debug Monitor"),
  irqReserved11: CpuIrq(id: 3, name: "Reserved11", description: "Reserved - do not use"),
  irqPendSV: CpuIrq(id: 2, name: "PendSV", description: "Pendable request for system service"),
  irqSysTick: CpuIrq(id: 1, name: "SysTick", description: "System Tick Timer"),
]
